### ISSUE TITLE
Needs more questions for quiz categories

### ISSUE THREAD

**Issue by KMSOMERS** [KMSOMERS/NeverHaveIEver2#1]
The arrays.xml file contains the questions for each category. 
You can contribute by adding questions to the string arrays.
Questions are in the format "Never have I Ever " + string from array
Great for the last push of hacktoberfest!

**Comment by ferrelucas** [comment]
Haha this app sounds cool. I am gonna add more lines in the xml and try it on my phone! :D :beer: :jack_o_lantern:
